### ISSUE TITLE
Android timelines and collaboration

### ISSUE THREAD

**Issue by stueynet** [blackuy/react-native-twilio-video-webrtc#13]
Wondering what the timelines are for Android and if you have a plan for that. We would love to contribute as well.

**Comment by bilby91** [comment]
Hello @stueynet, @slycoder was working on merging a working version he has with Android. We can try reaching him to get some status on the work. Either way any collaboration is more than welcome! I don't have Android experience so having someone that can contribute on that side it would be awesome.

**Comment by slycoder** [comment]
Hi all, I got sidetracked with some other work.  If someone else wants to help out, what I've got is all in https://github.com/healthcoda/react-native-twilio-video-android.

@bilby91  Maybe I should just commit the code sooner rather than later, even if the interface doesn't quite match yet, so that at least everyone can work off of this repo.  How does that sound?

**Comment by stueynet** [comment]
That's great guys. @andrewhl and @fhad-getmaple have a look but @slycoder I think as long as it doesn't break the ios side we'd be good with that. I definitely think that would make more sense to keep this as the core repo and we can contribute here.

**Comment by bilby91** [comment]
@slycoder As long as we don't change the JS interface I don't their will be a problem! Give it a try and let's start shaping this!

**Comment by rajesh1158** [comment]
@slycoder @bilby91  Any progress on the Android module? Was looking to integrate the android part into my first react native app. TIA.

**Comment by bilby91** [comment]
We are about to merge android @slycoder implementation. Stay tuned.

**Comment by bilby91** [comment]
Current implementation should support one participant in Android.
