### ISSUE TITLE
Why we don't update the library to npm package ?

### ISSUE THREAD

**Issue by ak1103dev** [blackuy/react-native-twilio-video-webrtc#141]

**Comment by slycoder** [comment]
Fwiw, I'd be in favor of that.

**Comment by Fallup** [comment]
Any plans for publishing the lib to the npm?
Last publish [happened 2 years ago](https://www.npmjs.com/package/react-native-twilio-video-webrtc)

It is inconvenient to keep own fork or having unstable dependency to this git repo itself.

**Comment by slycoder** [comment]
n.b. If you want to maintain stability you can peg this package to a particular commit sha in your package.json (I would highly recommend that for anything you're pulling from git!).

**Comment by belgamo** [comment]
Can you publish to the npm please? I will have to follow the tip from @slycoder but it would be much better if the lib was on npm.

**Comment by slycoder** [comment]
@belgamo I totally agree but I don't have access to the npm account for this repo =(.

**Comment by Balasnest** [comment]
@slycoder Better let's create and publish a new one. what do you think?

**Comment by fabiendem** [comment]
Bumping this thread.

@eduedix @gaston23 @bilby91 if anyone of you owns the [https://www.npmjs.com/package/react-native-twilio-video-webrtc](https://www.npmjs.com/package/react-native-twilio-video-webrtc) npm, are you able to transfer ownership to @slycoder if you no longer wish to maintain the library?

Otherwise we will have to create a new entry on npm.

**Comment by bilby91** [comment]
@slycoder , would you mind sending me your npm user over email ? I'll grant you write access to the npm repository!

**Comment by slycoder** [comment]
@bilby91  Sent you an email.

**Comment by slycoder** [comment]
This was recently pushed to npm.
