### ISSUE TITLE
Video Views appear black on screenshot

### ISSUE THREAD

**Issue by jedabero** [blackuy/react-native-twilio-video-webrtc#199]
### Steps to reproduce
1. Create a new project `react-native init NewProjectName`
2. Add [react-native-view-shot](https://github.com/gre/react-native-view-shot)
3. Add this library
4. You'll need at least two devices (either two android emulators, one emulator and one android phone, two android phones or two iphones)

I've setup a minimal project here
https://github.com/pluriza/twilio-view-shot
The creation of the accessToken can be done at https://www.twilio.com/console/video/runtime/testing-tools

### Expected behaviour
Screen captured with view-shot should show video views normally

### Actual behaviour
Screen captured with view-shot should shows video views as black boxes

### Environment
- **Node.js version**: v10.15.3
- **React Native version**: 0.59.8
- **React Native platform + platform version**: Android, 8.0 and 6.0 not tested on iOS

### react-native-twilio-video-webrtc
**Version**: "master"

I've also reported this to react-native-view-shot @ [issue 216](https://github.com/gre/react-native-view-shot/issues/216)

**Comment by jedabero** [comment]
I also check to see is this happened by using just the react-native-camera but no, view-shot works correctly there.
Maybe it's the way VideoView is rendered on screen?

**Comment by rolivegab** [comment]
Sometimes, for me, reboot android emulator device fixes the problem.

I already notice same problem with another camera applications showing black screen, like react-native-camera, or even the default native google camera application from emulated device, and reboot fixes all of then too.

It looks like the camera device was disconnected.

Also,
#289 has a fix to black screen visualization.
So maybe this issue is already fixed?

**Comment by Andriiklymiuk** [comment]
it is still an issue in the latest version
