### ISSUE TITLE
is DataTrack available?

### ISSUE THREAD

**Issue by UberMC** [blackuy/react-native-twilio-video-webrtc#263]
Looking to not only have audio and video but also send (stringified objects) back and forth between the users. On Twilio this is known as DataTrack and on openToken it's signaling. Is there anything in react-native-twilio-video-webrtc available like dataTrack?

https://www.twilio.com/docs/video/using-datatrack-api

**Comment by slycoder** [comment]
There's currently no support for that right now.  It should be pretty easy to add support for datatracks (you'd just need to copy paste some of the video/audio track events); I don't have a lot of bandwidth to work on this right now but if you wanna take a crack at it, I'd be happy to help give you guidance so that we can get a PR in here.

**Comment by UberMC** [comment]
I **succesfully** built the bridge for iOS and android dataTrack, works great (AND FAST!). and got approval from the company to release it publicly so I'll put in a pull request by Monday.

**Comment by samjbmason** [comment]
Is there any updat on if this PR is good to go? Would love access to data tracks

**Comment by slycoder** [comment]
This should already be on master.
