### ISSUE TITLE
Typescript Support/Rewrite in Typecsript 

### ISSUE THREAD

**Issue by nmasnadithya** [blackuy/react-native-twilio-video-webrtc#267]
I'm looking into using this in my workplace. And a strict rule at our workplace is to use typescript instead of javascript(Due to obvious reasons related to types). So, what I have to ask is, 

1. Would it be ok to rewrite the js code in typescript ? So, when compiled it'll be usable by both js and typescript.
2. If not why ? 

Please give me a quick reply, since I have to get my project up and running really quick.

**Comment by slycoder** [comment]
No objections from me if you want to typescript-ify things, as long as it still works on non-ts envs.

**Comment by kde3kko** [comment]
I'm working on a .d.ts to include in root folder to make like easier for typescript devs, I can submit a PR if it's ok!
That should be best of both worlds.
P.S. is this library still developed?
I see a lot of forks packaged in npm repository  but it's quite messy...

**Comment by slycoder** [comment]
Sure thing, I think a lot of people would be happy to see typescript definitions for this package.  PR away!

**Comment by kde3kko** [comment]
I'm working on it right now, I'm investigating if I can reuse some already existing Twilio type definitions from 
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/cd4a4e2db47f9642cf322fe109b5bfb3f6eb23c7/types/twilio-video
e.g. _Room_, _Participant_ etc.
instead of defining everything inside event callbacks as _any_, or redefining such types.
This might take some time since I still have to deeply understand how the conversion from native to js works...i'll let you know in the next couple of days!

**Comment by stefnnn** [comment]
Wow, just in time! Thanks a bunch @kde3kko ❤️
