### ISSUE TITLE
Anyone built VoIP app and callKit along with this library?

### ISSUE THREAD

**Issue by Balasnest** [blackuy/react-native-twilio-video-webrtc#378]
Let us know your thoughts and challenge if anyone has integrated VoIP and callKit using this library.

Actually I am in a starting stage of development utilizing with below lib:
**callKit for iOS** - https://github.com/react-native-webrtc/react-native-callkeep
**voip push** - https://github.com/react-native-webrtc/react-native-voip-push-notification

**Comment by stevelizcano** [comment]
I've done it. It's a bit of a pain, but mainly from understanding all of the concepts that work together. Other than that, it works well other than the fact that if you are answering while the phone is in a sleep state, the speaker does not turn on and needs to be turned on manually. This is because callkit itself doesn't enable the speaker.

**Comment by caglardurmus** [comment]
> I've done it. It's a bit of a pain, but mainly from understanding all of the concepts that work together. Other than that, it works well other than the fact that if you are answering while the phone is in a sleep state, the speaker does not turn on and needs to be turned on manually. This is because callkit itself doesn't enable the speaker.

How can i turn it on manually? I have this problem too.

**Comment by malord** [comment]
I've implemented it but I seem to have the opposite problem to stevelizcano, my app immediately connects using the loud speaker (as opposed to the ear speaker... not sure if there's a better term for that speaker) and I can't toggle it!
