### ISSUE TITLE
TwilioVideoLocalView aka <LocalView /> is squished on Android.

### ISSUE THREAD

**Issue by max-docly** [blackuy/react-native-twilio-video-webrtc#436]
### Steps to reproduce
1. Start a call on android.

### Expected behaviour
I have added 100% height and width to the `<LocalView />` component and it works for IOS as you can see from the the picture below:

How it should look (this is on IOS):
<img src="https://user-images.githubusercontent.com/61692340/103899747-21413d80-50f7-11eb-8485-caf09c8f0079.jpg" width="40%"/>

### Actual behaviour
But on Android it looks like this, with the same styling and everything.

<img src="https://user-images.githubusercontent.com/61692340/103899808-39b15800-50f7-11eb-9b86-0891354f1c5b.jpg" width="40%"/>

If you zoom in and look carefully you can see that the actual camera image is spreading outside its <View/> container and also not taking up its full height. 

### Environment
- **Node.js version: 7.4.4**:
- **React Native version: 0.63.3**:
- **React Native platform + platform version**: Android: Honor 9, version: 9.1.0.210, IOS: Iphone X, version: 14.1

### react-native-twilio-video-webrtc
**Version**:  master

**Comment by slycoder** [comment]
So if the view is using a scale-to-fit approach for the local view (that is the underlying stream will be scaled down until it fits in the bounds of the view it's contained in) you could see the effect you have there if the underlying stream dimensions were different (because there are different cameras).  Would it be possible to report what those dimensions are? 

One helpful debugging tool I've found in the past is to add a border to the view; that way you can see how the video is filling up the space allocated to it.

**Comment by max-docly** [comment]
Hello, thank you for the reply. However we already found a way of solving this by adding this property to the component `scaleType="fill"` although it was not easy to find that this prop existed. It would be great if you could add all possible props to your docs in the future. Although if I've missed this somewhere please do let me know! @slycoder

**Comment by slycoder** [comment]
Ah, the docs are definitely in need of some TLC.  I'll do that in #453
