### ISSUE TITLE
Compatibility with React-Native 0.48.3 — Linking for iOS

### ISSUE THREAD

**Issue by viniychuk** [blackuy/react-native-twilio-video-webrtc#52]
### Steps to reproduce
1. react-init Example
2. follow README for ios — `yarn add https://github.com/blackuy/react-native-twilio-video-webrtc` , create the `Podfile`, do `pod install`
3. go to ios folder `cd ios`
4. execute `pod install`
5. add signing configuration for the xcode
6. try to archive a project — it'll say that `react-native-twilio-video-webrtc` is not found.

I tried to find workaround and got your `Example` project and bumped react-native to 0.45(0.46..0.48) and reinstalling pods — got almost the same issues, just with a different error. 
It seems like the issue here is with the `packager` changes because according to the release notes there weren't many changes in the `react-native` itself.

**important** App runs perfectly fine using `react-native` up to 0.48.3 in both Debug and Release modes, error happens only when you're trying to Archive!

### Environment
- **Node.js version**: 8.1
- **React Native version**: 0.48.3
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**:  "master"

**Comment by viniychuk** [comment]
Podfile that does the best job so far:
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'Example' do
  pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

  pod 'React',
    :path => '../node_modules/react-native',
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTImage",
      "RCTGeolocation",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "BatchedBridge"
    ]

  pod 'react-native-twilio-video-webrtc', path: '../node_modules/react-native-twilio-video-webrtc'
end
```

**Comment by viniychuk** [comment]
@bilby91 are you working with iOS mostly? Do you use latest react native and if so — does it work for you as a pod or you simply copied project's files and linked them manually?

**Comment by bilby91** [comment]
Hey,

I'll review this in the weekend. Right now I'm not working on react-native. Let me.know if you can get a working PR please!

Most of my work was on iOS as you mentioned!

Martín

On Thu, Sep 21, 2017 at 20:29 Alexandr Viniychuk

<
mailto:Alexandr Viniychuk <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/bilby91
are you working with iOS mostly? Do you use latest react native and if so — does it work for you as a pod or you simply copied project's files and linked them manually?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/blackuy/react-native-twilio-video-webrtc/issues/52#issuecomment-331309208
, or
