### ISSUE TITLE
Data track support

### ISSUE THREAD

**Issue by petros9282** [blackuy/react-native-twilio-video-webrtc#61]
Hi guys. I just saw that Twillio added data track support on the native clients. Are there any plans for you to add it on the RN project?

**Comment by bilby91** [comment]
Hello @petros9282 !

We in the same situation as described in #62 :(. Not a lot of time at the moment. What platform are you using in RN ?

**Comment by georgewwindsor** [comment]
I plan on supporting this within 1 month,unless anyone else is attacking it? @bilby91  @slycoder

**Comment by slycoder** [comment]
I hadn't planned on working on it.  I'm sure the contribution will be much appreciated @georgewwindsor !

**Comment by bilby91** [comment]
@georgewwindsor That would be awesome. For the moment I'm not planning on working on this. Do you need this for both implementations ? 

This would be an important bump in the library since we are going to move to Twilio 2.0. Probably good time to fix some annoying issues like being able to install the package via npm, have a CHANGELOG, etc. I can work on the later ones probably.

**Comment by cipriancaba** [comment]
Hey @georgewwindsor maybe we can sync in #64 I can try and help on the iOS side
