### ISSUE TITLE
Migrate to TwilioVideo 2.0

### ISSUE THREAD

**Issue by bilby91** [blackuy/react-native-twilio-video-webrtc#64]
In order to support #61 we need to first support TwilioVideo 2.0

In order to do that we need to:

- [ ] Upgrade iOS native integration to 2.0
- [ ] Upgrade Android native integration to 2.0
- [ ] Adapt JS API if needed. We will find out this based on the changes in 2.0 API.

@petros9282 you want to start working on this ? I can help out with the testing and doing code reviews at the moment.

@slycoder Can you help out with the Android code reviews ?

**Comment by slycoder** [comment]
I'd be happy to help out!

**Comment by kcedric** [comment]
Do you guys have any update on supporting 2.0.0 & specially for iOS ?

**Comment by cipriancaba** [comment]
I can give a hand with the iOS implementation for iOS, but after giving the changelog a look, it seems that there are many breaking changes, which means that probably the API will need to change as well

Also, I've contacted Twilio regarding the issue https://github.com/twilio/video-quickstart-objc/issues/62 and they said they will be working towards a react-native implementation.. However, they didn't offer a concrete schedule saying it will take weeks.. Maybe if we could all focus our efforts this can be done sooner rather than later

**Comment by jadbox** [comment]
What's the current status?

**Comment by cipriancaba** [comment]
@jadbox Not really stable but you can hack your way around it... i've altered my own fork for my project's needs but was hoping to see more involvement in this repo, especially on the android side

**Comment by slycoder** [comment]
@cipriancaba I'd be up for helping out on the android side.

**Comment by slycoder** [comment]
This is up on master now.  Closing out.
