### ISSUE TITLE
Audio from streams get muted

### ISSUE THREAD

**Issue by cipriancaba** [blackuy/react-native-twilio-video-webrtc#77]
### Steps to reproduce
1. Have multiple clients connect to a room
2. They can all hear each other
3. Play a video with sound -> Sound suddenly stops from all streams

### Expected behaviour
Stream sound should be mixed with video sound

### Actual behaviour
Stream sound is not working anymore

### Environment
- **Node.js version**: 8.2
- **React Native version**: 0.51
- **React Native platform + platform version**: iOS 11.2

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

Any ideas on where to get started investigating this?

**Comment by bilby91** [comment]
Hello, @cipriancaba 

What do you mean by `Stream sound is not working anymore` ? Was it working before for you. I'm not sure if what you are trying to do is possible with the current implementation.

**Comment by cipriancaba** [comment]
Hey @bilby91 I was referring to the issue described here: https://github.com/twilio/video-quickstart-objc/issues/62

It's not probably something that is on the react native wrapper, just a twilio sdk limitation.. 

Was just wondering if someone was able to work around the issue as I've tried with the suggestion from the referred issue but with no success

As related to your question, the stream sound is working perfectly until I play the video.. once I do that however, all the sounds from the stream get muted

**Comment by idajimenez** [comment]
Hi @cipriancaba may I know what version are you using for `react-native-twilio-video-webrtc` and `TwilioVideo`? I am also experiencing low/muted audio whenever the call is made between android and ios. Thank you!

**Comment by marymhart** [comment]
Hello, writing to note that this is still an issue
### Steps to reproduce
1. Start a call from iOS & answer on another device/web. Note that participants can hear each other.
2. Our app has a webview that plays sounds using an html audio element whenever messages are received. When one of these sounds are played then audio permanently stops for all participants in the call. We are also playing sounds in react-native but those work fine & do not stop the audio. Sounds from other apps also work fine.
### Expected behaviour
Audio should not cut out when a sound is played in the webview

### Actual behaviour
Audio permanently cuts out for all users when a sound is played in the webview

### Environment
- **Node.js version**: 12.18.1
- **React Native version**: 0.61.5
- **React Native platform + platform version**: iOS 14.1

### react-native-twilio-video-webrtc
**Version**: master
